version: '3.8'
services:
  fulusin:
    build:
      context: .
      dockerfile: deployment/Dockerfile
      container_name: fulusin
      ports:
        - '3000:3000'
      environment:
        - NODE_ENV=production
      restart: always
